#!/usr/bin/ruby

fifo = `a=$(mktemp); rm $a; mkfifo $a; echo $a`.chomp
p fifo

fork {
  cmd = ""
  logging = false
  File.open("data.txt", "a") { |f|
    File.open(fifo, "r").each { |line|
      if (m = line.match(/^([^ ]+) read\((.).*"(.*)".* ([0-9]+)$/))
        if m[2] == "4" && m[4].length == 1
          if m[3] == "\\r"
            logging = true  if cmd.match(/#START/)
            logging = false if cmd.match(/#STOP/)
            cmd = ""
          else
            cmd += m[3]
          end
          f.write "#{m[1]} KEY '#{m[3]}'\n" if logging
        elsif m[2] == "3"
          f.write "#{m[1]} DATA #{m[4]}\n" if logging
        end
      end
    }
  }
}

exec("strace","-ttt","-o",fifo,"--","ssh",*ARGV)
